### ISSUE TITLE
Create slide deck for final presentation.

### ISSUE THREAD

**Issue by JWFeatherstone** [JWFeatherstone/fitlit-adriane-houda-sam-john#152]
**Tasks**

- [ ] Create an empty Google Slides deck and share edit access with the group.
- [ ] Build out an initial skeleton and bullet point out the content and any desired graphics or images.
- [ ] Finish the final formatting.

**Guidance**
Part of your future interviews will be talking about your application, code, and decision process as a developer, and this presentation is great practice for that situation. Your group’s presentation should have slides that include:

- What was your track?
- Given the vague track feature goal, what was your process like to go from idea to code to finished product?
- What was challenging about your track?
- What work were you proud of from your track?
- What did you observe during the usability test, and did you change anything about your application?
- How close were your time estimations for certain tasks? Did you overestimate or underestimate, and what do you think the cause was of the difference?
- Aim for the presentation to take about 10 minutes.

**Interview Questions**
As a group, you will respond to high-level technical questions, interview-style. These questions will all relate to the work you’ve done on this project. For example, “Describe what a POST request is and why we might perform one.”

Individually, you will be asked a question at random to respond to. You must give an attempt at responding to it before passing it off to a group member if you’re unsure. Imagine you don’t know the answer to a question on a technical interview, you won’t simply say “I don’t know”. Will you try to take an educated guess? Will you say you’re unsure? Will you try to explain by example?

If the evaluator is left wanting a bit more from your response, they may choose to continue to ask a follow-up question to you - or they may open it up to volunteers in the group to assist.

If you get a question wrong, it will not count against you! This is really all about getting some practice answering interview-style questions.

**Comment by JWFeatherstone** [comment]
[Here's the starter slide deck.](https://docs.google.com/presentation/d/16GwLX8vaceq4rTkXrlLs3o-SydTFw_Q8-jKfrQaDiuI/edit?usp=sharing)
