### ISSUE TITLE
Storing and Manipulating User Data

### ISSUE THREAD

**Issue by JWFeatherstone** [JWFeatherstone/fitlit-adriane-houda-sam-john#4]
## To-Do

- [ ] Plan approach and delegate subtasks
- [ ] Build tests for user class and its methods
- [ ] Build user class and methods
